// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfDFcxrfZcAH1s5zIaptCxlhJn2vqzZsk',
    appId: '1:655317403621:web:68803e9d0fb21d0488910c',
    messagingSenderId: '655317403621',
    projectId: 'e-commerce-iti-bff04',
    authDomain: 'e-commerce-iti-bff04.firebaseapp.com',
    storageBucket: 'e-commerce-iti-bff04.appspot.com',
    measurementId: 'G-5N38S0NR5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-QdxTRzgoWYYxMcZIxgKwxsiXrPVZ0yE',
    appId: '1:655317403621:android:095c179de9612a5488910c',
    messagingSenderId: '655317403621',
    projectId: 'e-commerce-iti-bff04',
    storageBucket: 'e-commerce-iti-bff04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR7lqWE9iVE6tK3cN81_44TObnbcpOIVY',
    appId: '1:655317403621:ios:ca53bddf5b475e1c88910c',
    messagingSenderId: '655317403621',
    projectId: 'e-commerce-iti-bff04',
    storageBucket: 'e-commerce-iti-bff04.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR7lqWE9iVE6tK3cN81_44TObnbcpOIVY',
    appId: '1:655317403621:ios:ca53bddf5b475e1c88910c',
    messagingSenderId: '655317403621',
    projectId: 'e-commerce-iti-bff04',
    storageBucket: 'e-commerce-iti-bff04.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfDFcxrfZcAH1s5zIaptCxlhJn2vqzZsk',
    appId: '1:655317403621:web:8d6c646ec0ac307e88910c',
    messagingSenderId: '655317403621',
    projectId: 'e-commerce-iti-bff04',
    authDomain: 'e-commerce-iti-bff04.firebaseapp.com',
    storageBucket: 'e-commerce-iti-bff04.appspot.com',
    measurementId: 'G-7H21Z060EZ',
  );
}
